input_file: "data/raw/enrollment_data.csv"
plot_dir: "plots"
save_plots: false  # Set to true to save plots to disk

# Analysis parameters
levels:
  - "Undergraduate"
  - "Graduate"
  - "All Levels"

residencies:
  - "Domestic"
  - "International"
  - "All Residencies"

metrics:
  - "Headcount"
  - "FTE"

# Forecasting parameters
forecast_steps: 9

# Model configuration
models:
  seasonal_naive_params:
    seasonal_periods: 4

  ets_params:
    seasonal_periods: 4
    damped_trend: true
    use_boxcox: true

  arima_params:
    seasonal_periods: 4
    max_order: [2, 1, 2]
    max_seasonal_order: [1, 1, 1, 4]
